In [2]:
import numpy as np
import pandas as pd

In [3]:
matches_df = pd.read_csv('data/matches.csv')

In [6]:
matches_df['umpire3'].value_counts().idxmax()

'Nitin Menon'

In [4]:
matches_df  = matches_df['umpire3'].fillna(matches_df['umpire3'].value_counts().idxmax())

In [8]:
deliveries_df  = pd.read_csv('data/deliveries.csv')
deliveries_df.shape

(179078, 21)

In [9]:
upper_limit = deliveries_df.total_runs.std()
upper_limit

1.6054216425608103

In [7]:
lower_limit = deliveries_df.total_runs.mean()-deliveries_df.total_runs.std()
lower_limit

-0.29152490482641524

In [14]:
deliveries_df[(deliveries_df['total_runs'] > 6)].shape

(118, 21)

In [11]:
upper_lim = deliveries_df['total_runs'].quantile(.95)
lower_lim = deliveries_df['total_runs'].quantile(.05)
print(upper_lim)
print(b)

deliveries_df['total_runs'].mean()

4.0
0.0

1.313896737734395

In [10]:
deliveries_df[deliveries_df.batting_team.isin( deliveries_df.batting_team.value_counts().nlargest(9).index)]
# deliveries_df.batting_team.value_counts().nlargest(9)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
5,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
7,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,A Choudhary,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
9,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,3,DA Warner,S Dhawan,A Choudhary,0,...,0,0,1,0,0,1,1,NaN,NaN,NaN
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh
12,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,6,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
14,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
15,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,2,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
16,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,3,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
17,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,4,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,3,0,3,NaN,NaN,NaN
18,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,5,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
19,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,6,MC Henriques,S Dhawan,TS Mills,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
20,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,1,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
21,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,2,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
22,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,3,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
23,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,4,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
24,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,5,MC Henriques,S Dhawan,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
25,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,4,6,S Dhawan,MC Henriques,YS Chahal,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
26,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,1,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
27,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,2,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
28,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,3,S Dhawan,MC Henriques,S Aravind,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
29,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,5,4,MC Henriques,S Dhawan,S Aravind,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179048,11415,2,Chennai Super Kings,Mumbai Indians,16,1,DJ Bravo,SR Watson,SL Malinga,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179049,11415,2,Chennai Super Kings,Mumbai Indians,16,2,DJ Bravo,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179050,11415,2,Chennai Super Kings,Mumbai Indians,16,3,SR Watson,DJ Bravo,SL Malinga,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
179051,11415,2,Chennai Super Kings,Mumbai Indians,16,4,SR Watson,DJ Bravo,SL Malinga,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
179052,11415,2,Chennai Super Kings,Mumbai Indians,16,5,SR Watson,DJ Bravo,SL Malinga,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
179053,11415,2,Chennai Super Kings,Mumbai Indians,16,6,SR Watson,DJ Bravo,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179054,11415,2,Chennai Super Kings,Mumbai Indians,17,1,SR Watson,DJ Bravo,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179055,11415,2,Chennai Super Kings,Mumbai Indians,17,2,DJ Bravo,SR Watson,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179056,11415,2,Chennai Super Kings,Mumbai Indians,17,3,SR Watson,DJ Bravo,JJ Bumrah,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
179057,11415,2,Chennai Super Kings,Mumbai Indians,17,4,SR Watson,DJ Bravo,JJ Bumrah,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
179058,11415,2,Chennai Super Kings,Mumbai Indians,17,5,SR Watson,DJ Bravo,JJ Bumrah,0,...,1,0,0,0,1,1,2,NaN,NaN,NaN
179059,11415,2,Chennai Super Kings,Mumbai Indians,17,6,DJ Bravo,SR Watson,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179060,11415,2,Chennai Super Kings,Mumbai Indians,18,1,DJ Bravo,SR Watson,KH Pandya,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179061,11415,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179062,11415,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179063,11415,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,6,0,6,NaN,NaN,NaN
179064,11415,2,Chennai Super Kings,Mumbai Indians,18,5,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
179065,11415,2,Chennai Super Kings,Mumbai Indians,18,6,SR Watson,DJ Bravo,KH Pandya,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179066,11415,2,Chennai Super Kings,Mumbai Indians,19,1,SR Watson,DJ Bravo,JJ Bumrah,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179067,11415,2,Chennai Super Kings,Mumbai Indians,19,2,DJ Bravo,SR Watson,JJ Bumrah,0,...,0,0,0,0,0,0,0,DJ Bravo,caught,Q de Kock
179068,11415,2,Chennai Super Kings,Mumbai Indians,19,3,RA Jadeja,SR Watson,JJ Bumrah,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179069,11415,2,Chennai Super Kings,Mumbai Indians,19,4,RA Jadeja,SR Watson,JJ Bumrah,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
179070,11415,2,Chennai Super Kings,Mumbai Indians,19,5,RA Jadeja,SR Watson,JJ Bumrah,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179071,11415,2,Chennai Super Kings,Mumbai Indians,19,6,RA Jadeja,SR Watson,JJ Bumrah,0,...,4,0,0,0,4,4,8,NaN,NaN,NaN
179072,11415,2,Chennai Super Kings,Mumbai Indians,20,1,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [11]:
matches_df.isna().sum()

0

In [12]:
deliveries_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [14]:
# deliveries_df['total_runs_over'] = deliveries_df.groupby(['match_id','inning',over']).total_runs.transform('sum')
# deliveries_df.head(6)
# fm = deliveries_df[deliveries_df.match_id = 1]
# deliveries_df.groupby(['match_id','over']).total_runs.sum().head()
# fm
# deliveries_df[(deliveries_df.match_id == 1) & (deliveries_df.over == 1)]
deliveries_df['total_runs_over'] = deliveries_df.groupby(['match_id','inning','over']).total_runs.transform('sum')
deliveries_df.head(15)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder,total_runs_over
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,NaN,NaN,NaN,7
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,NaN,NaN,NaN,7
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,4,0,4,NaN,NaN,NaN,7
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,NaN,NaN,NaN,7
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,2,2,NaN,NaN,NaN,7
5,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,6,S Dhawan,DA Warner,TS Mills,0,...,0,0,0,0,0,0,NaN,NaN,NaN,7
6,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,7,S Dhawan,DA Warner,TS Mills,0,...,1,0,0,0,1,1,NaN,NaN,NaN,7
7,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,1,S Dhawan,DA Warner,A Choudhary,0,...,0,0,0,1,0,1,NaN,NaN,NaN,16
8,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,2,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,4,0,4,NaN,NaN,NaN,16
9,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,3,DA Warner,S Dhawan,A Choudhary,0,...,0,1,0,0,1,1,NaN,NaN,NaN,16
10,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,4,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,6,0,6,NaN,NaN,NaN,16
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,DA Warner,caught,Mandeep Singh,16
12,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,6,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,0,0,0,NaN,NaN,NaN,16
13,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,7,MC Henriques,S Dhawan,A Choudhary,0,...,0,0,0,4,0,4,NaN,NaN,NaN,16
14,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,3,1,S Dhawan,MC Henriques,TS Mills,0,...,0,0,0,1,0,1,NaN,NaN,NaN,6

In [54]:
deliveries_df['bin'] = pd.cut(deliveries_df['batsman_runs'], bins=[0,0.9,3.9,6.1], labels=["zero", "Single", "Boundaries"], include_lowest=True)

In [55]:
deliveries_df.bin

0               zero
1               zero
2         Boundaries
3               zero
4               zero
5               zero
6               zero
7             Single
8         Boundaries
9               zero
10        Boundaries
11              zero
12              zero
13        Boundaries
14            Single
15              zero
16              zero
17            Single
18            Single
19            Single
20              zero
21            Single
22              zero
23            Single
24            Single
25            Single
26            Single
27            Single
28            Single
29            Single
             ...
179048    Boundaries
179049        Single
179050    Boundaries
179051    Boundaries
179052    Boundaries
179053        Single
179054        Single
179055        Single
179056          zero
179057          zero
179058        Single
179059        Single
179060        Single
179061    Boundaries
179062    Boundaries
179063    Boundaries
179064          zero
179065        Single
179066        Single
179067          zero
179068        Single
179069          zero
179070        Single
179071    Boundaries
179072        Single
179073        Single
179074        Single
179075        Single
179076        Single
179077          zero
Name: bin, Length: 179078, dtype: category
Categories (3, object): [zero < Single < Boundaries]

In [57]:
deliveries_df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder', 'total_runs_over', 'bin'],
      dtype='object')

In [63]:
deliveries_df.dismissal_kind.unique()

array([nan, 'caught', 'bowled', 'run out', 'lbw', 'caught and bowled',
       'stumped', 'retired hurt', 'hit wicket', 'obstructing the field'],
      dtype=object)

In [61]:
deliveries_df['dismissal_type'] = deliveries_df.dismissal_kind.map({'caught' : 'caught and bowled', 'bowled' : 'caught and bowled', 'retired hurt' : 'others', 'hit wicket' : 'others',  'obstructing the field' : 'others'})

In [62]:
deliveries_df.dismissal_type.unique()

array([nan, 'caught and bowled', 'others'], dtype=object)

In [31]:
dismissals_df = deliveries_df[deliveries_df['dismissal_kind'].notna()]
dismissals_df.dismissal_kind.value_counts()
dismissalkind_df = pd.get_dummies(dismissals_df['dismissal_kind'])
dismissalkind_df
pd.concat([dismissals_df, dismissalkind_df], axis=1)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,score_bin,bowled,caught,caught and bowled,hit wicket,lbw,obstructing the field,retired hurt,run out,stumped
11,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,2,5,DA Warner,S Dhawan,A Choudhary,0,...,dot,0,1,0,0,0,0,0,0,0
64,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,11,3,S Dhawan,MC Henriques,STR Binny,0,...,dot,0,1,0,0,0,0,0,0,0
94,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,16,2,MC Henriques,Yuvraj Singh,YS Chahal,0,...,dot,0,1,0,0,0,0,0,0,0
116,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,19,4,Yuvraj Singh,DJ Hooda,TS Mills,0,...,dot,1,0,0,0,0,0,0,0,0
160,1,2,Royal Challengers Bangalore,Sunrisers Hyderabad,6,4,Mandeep Singh,CH Gayle,Rashid Khan,0,...,dot,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179019,11415,2,Chennai Super Kings,Mumbai Indians,11,3,AT Rayudu,SR Watson,JJ Bumrah,0,...,dot,0,1,0,0,0,0,0,0,0
179033,11415,2,Chennai Super Kings,Mumbai Indians,13,5,SR Watson,MS Dhoni,HH Pandya,0,...,Single,0,0,0,0,0,0,0,1,0
179067,11415,2,Chennai Super Kings,Mumbai Indians,19,2,DJ Bravo,SR Watson,JJ Bumrah,0,...,dot,0,1,0,0,0,0,0,0,0
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,Single,0,0,0,0,0,0,0,1,0
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,dot,0,0,0,0,1,0,0,0,0

In [19]:
 deliveries_df['score_bin'] = pd.cut(deliveries_df['batsman_runs'], bins=[0,0.9,3.9,6.1], labels=["dot", "Single", "Boundaries"], include_lowest=True)

In [32]:
deliveries_df.dismissal_kind.value_counts()

caught                   5348
bowled                   1581
run out                   852
lbw                       540
stumped                   278
caught and bowled         211
retired hurt               12
hit wicket                 10
obstructing the field       2
Name: dismissal_kind, dtype: int64

Load the dataset with date

In [76]:
df = pd.read_csv('data/matches.csv', parse_dates=['date'])

Convert to specific date format /
pd.to_datetime(data,format=%d-%m-%y)

In [77]:
# pd.to_datetime
df.date.tail(20)

736   2019-04-23
737   2019-04-24
738   2019-04-25
739   2019-04-26
740   2019-04-27
741   2019-04-28
742   2019-04-28
743   2019-04-29
744   2019-04-30
745   2019-01-05
746   2019-02-05
747   2019-03-05
748   2019-04-05
749   2019-04-05
750   2019-05-05
751   2019-05-05
752   2019-07-05
753   2019-08-05
754   2019-10-05
755   2019-12-05
Name: date, dtype: datetime64[ns]

Separate the year and month and day

In [80]:
df.date.dt.day

0      5
1      6
2      7
3      8
4      8
      ..
751    5
752    5
753    5
754    5
755    5
Name: date, Length: 756, dtype: int64

Print the day name

In [81]:
df.date.dt.day_name()

0      Wednesday
1       Thursday
2         Friday
3       Saturday
4       Saturday
         ...
751       Sunday
752       Friday
753       Monday
754     Saturday
755     Thursday
Name: date, Length: 756, dtype: object

Print today's date

In [83]:
from datetime import date
date.today()

datetime.date(2019, 11, 16)